# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(708, 466)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(9, 10, 691, 421))
        self.tabWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tabWidget.setObjectName("tabWidget")
        self.Main = QtWidgets.QWidget()
        self.Main.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Main.setObjectName("Main")
        self.gridGroupBox = QtWidgets.QGroupBox(self.Main)
        self.gridGroupBox.setGeometry(QtCore.QRect(10, 200, 261, 181))
        self.gridGroupBox.setFlat(False)
        self.gridGroupBox.setCheckable(False)
        self.gridGroupBox.setObjectName("gridGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridGroupBox)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_ac = QtWidgets.QLineEdit(self.gridGroupBox)
        self.line_ac.setObjectName("line_ac")
        self.gridLayout_2.addWidget(self.line_ac, 4, 1, 1, 1)
        self.line_dose_per_frame = QtWidgets.QLineEdit(self.gridGroupBox)
        self.line_dose_per_frame.setObjectName("line_dose_per_frame")
        self.gridLayout_2.addWidget(self.line_dose_per_frame, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.line_cs = QtWidgets.QLineEdit(self.gridGroupBox)
        self.line_cs.setObjectName("line_cs")
        self.gridLayout_2.addWidget(self.line_cs, 3, 1, 1, 1)
        self.line_apix = QtWidgets.QLineEdit(self.gridGroupBox)
        self.line_apix.setObjectName("line_apix")
        self.gridLayout_2.addWidget(self.line_apix, 1, 1, 1, 1)
        self.line_kV = QtWidgets.QLineEdit(self.gridGroupBox)
        self.line_kV.setEnabled(True)
        self.line_kV.setInputMethodHints(QtCore.Qt.ImhNone)
        self.line_kV.setObjectName("line_kV")
        self.gridLayout_2.addWidget(self.line_kV, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_60.setObjectName("label_60")
        self.gridLayout_2.addWidget(self.label_60, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_61.setObjectName("label_61")
        self.gridLayout_2.addWidget(self.label_61, 1, 2, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_62.setObjectName("label_62")
        self.gridLayout_2.addWidget(self.label_62, 2, 2, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_63.setObjectName("label_63")
        self.gridLayout_2.addWidget(self.label_63, 3, 2, 1, 1)
        self.formGroupBox = QtWidgets.QGroupBox(self.Main)
        self.formGroupBox.setGeometry(QtCore.QRect(9, 9, 671, 181))
        self.formGroupBox.setObjectName("formGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.formGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.formGroupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.btnGain = QtWidgets.QPushButton(self.formGroupBox)
        self.btnGain.setObjectName("btnGain")
        self.gridLayout.addWidget(self.btnGain, 4, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.formGroupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radio_tif = QtWidgets.QRadioButton(self.formGroupBox)
        self.radio_tif.setObjectName("radio_tif")
        self.horizontalLayout.addWidget(self.radio_tif)
        self.radio_mrc = QtWidgets.QRadioButton(self.formGroupBox)
        self.radio_mrc.setObjectName("radio_mrc")
        self.horizontalLayout.addWidget(self.radio_mrc)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 1, 1, 1)
        self.line_Gain = QtWidgets.QLineEdit(self.formGroupBox)
        self.line_Gain.setObjectName("line_Gain")
        self.gridLayout.addWidget(self.line_Gain, 4, 1, 1, 1)
        self.line_OutputDir = QtWidgets.QLineEdit(self.formGroupBox)
        self.line_OutputDir.setObjectName("line_OutputDir")
        self.gridLayout.addWidget(self.line_OutputDir, 3, 1, 1, 1)
        self.btnOutputDir = QtWidgets.QPushButton(self.formGroupBox)
        self.btnOutputDir.setObjectName("btnOutputDir")
        self.gridLayout.addWidget(self.btnOutputDir, 3, 2, 1, 1)
        self.btnInputDir = QtWidgets.QPushButton(self.formGroupBox)
        self.btnInputDir.setObjectName("btnInputDir")
        self.gridLayout.addWidget(self.btnInputDir, 2, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.GPU_0 = QtWidgets.QCheckBox(self.formGroupBox)
        self.GPU_0.setObjectName("GPU_0")
        self.horizontalLayout_2.addWidget(self.GPU_0)
        self.GPU_1 = QtWidgets.QCheckBox(self.formGroupBox)
        self.GPU_1.setObjectName("GPU_1")
        self.horizontalLayout_2.addWidget(self.GPU_1)
        self.GPU_2 = QtWidgets.QCheckBox(self.formGroupBox)
        self.GPU_2.setObjectName("GPU_2")
        self.horizontalLayout_2.addWidget(self.GPU_2)
        self.GPU_3 = QtWidgets.QCheckBox(self.formGroupBox)
        self.GPU_3.setObjectName("GPU_3")
        self.horizontalLayout_2.addWidget(self.GPU_3)
        self.GPU_4 = QtWidgets.QCheckBox(self.formGroupBox)
        self.GPU_4.setObjectName("GPU_4")
        self.horizontalLayout_2.addWidget(self.GPU_4)
        self.GPU_5 = QtWidgets.QCheckBox(self.formGroupBox)
        self.GPU_5.setObjectName("GPU_5")
        self.horizontalLayout_2.addWidget(self.GPU_5)
        self.GPU_6 = QtWidgets.QCheckBox(self.formGroupBox)
        self.GPU_6.setObjectName("GPU_6")
        self.horizontalLayout_2.addWidget(self.GPU_6)
        self.GPU_7 = QtWidgets.QCheckBox(self.formGroupBox)
        self.GPU_7.setObjectName("GPU_7")
        self.horizontalLayout_2.addWidget(self.GPU_7)
        self.GPU_8 = QtWidgets.QCheckBox(self.formGroupBox)
        self.GPU_8.setObjectName("GPU_8")
        self.horizontalLayout_2.addWidget(self.GPU_8)
        self.GPU_9 = QtWidgets.QCheckBox(self.formGroupBox)
        self.GPU_9.setObjectName("GPU_9")
        self.horizontalLayout_2.addWidget(self.GPU_9)
        self.gridLayout.addLayout(self.horizontalLayout_2, 6, 1, 1, 1)
        self.line_InputDir = QtWidgets.QLineEdit(self.formGroupBox)
        self.line_InputDir.setObjectName("line_InputDir")
        self.gridLayout.addWidget(self.line_InputDir, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.formGroupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.formGroupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.formGroupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.tabWidget.addTab(self.Main, "")
        self.Motioncor = QtWidgets.QWidget()
        self.Motioncor.setObjectName("Motioncor")
        self.groupBox_2 = QtWidgets.QGroupBox(self.Motioncor)
        self.groupBox_2.setGeometry(QtCore.QRect(180, 10, 151, 210))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.motioncor_FmDose = QtWidgets.QLineEdit(self.groupBox_2)
        self.motioncor_FmDose.setEnabled(False)
        self.motioncor_FmDose.setAutoFillBackground(False)
        self.motioncor_FmDose.setReadOnly(True)
        self.motioncor_FmDose.setObjectName("motioncor_FmDose")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.motioncor_FmDose)
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.motioncor_FtBin = QtWidgets.QLineEdit(self.groupBox_2)
        self.motioncor_FtBin.setObjectName("motioncor_FtBin")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.motioncor_FtBin)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.motioncor_InitDose = QtWidgets.QLineEdit(self.groupBox_2)
        self.motioncor_InitDose.setObjectName("motioncor_InitDose")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.motioncor_InitDose)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.motioncor_Patch = QtWidgets.QLineEdit(self.groupBox_2)
        self.motioncor_Patch.setPlaceholderText("")
        self.motioncor_Patch.setObjectName("motioncor_Patch")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.motioncor_Patch)
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.motioncor_Throw = QtWidgets.QLineEdit(self.groupBox_2)
        self.motioncor_Throw.setObjectName("motioncor_Throw")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.motioncor_Throw)
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        self.label_28.setObjectName("label_28")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.motioncor_Mag = QtWidgets.QLineEdit(self.groupBox_2)
        self.motioncor_Mag.setObjectName("motioncor_Mag")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.motioncor_Mag)
        self.groupBox_4 = QtWidgets.QGroupBox(self.Motioncor)
        self.groupBox_4.setGeometry(QtCore.QRect(340, 10, 161, 210))
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_6 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.motioncor_Iter = QtWidgets.QLineEdit(self.groupBox_4)
        self.motioncor_Iter.setPlaceholderText("")
        self.motioncor_Iter.setObjectName("motioncor_Iter")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.motioncor_Iter)
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        self.label_27.setObjectName("label_27")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.motioncor_Tilt = QtWidgets.QLineEdit(self.groupBox_4)
        self.motioncor_Tilt.setObjectName("motioncor_Tilt")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.motioncor_Tilt)
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setObjectName("label_21")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.motioncor_Group = QtWidgets.QLineEdit(self.groupBox_4)
        self.motioncor_Group.setObjectName("motioncor_Group")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.motioncor_Group)
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setObjectName("label_22")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.motioncor_FmRef = QtWidgets.QLineEdit(self.groupBox_4)
        self.motioncor_FmRef.setObjectName("motioncor_FmRef")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.motioncor_FmRef)
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setObjectName("label_23")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.motioncor_RotGain = QtWidgets.QLineEdit(self.groupBox_4)
        self.motioncor_RotGain.setObjectName("motioncor_RotGain")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.motioncor_RotGain)
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setObjectName("label_24")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.motioncor_FlipGain = QtWidgets.QLineEdit(self.groupBox_4)
        self.motioncor_FlipGain.setObjectName("motioncor_FlipGain")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.motioncor_FlipGain)
        self.groupBox_11 = QtWidgets.QGroupBox(self.Motioncor)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 10, 161, 94))
        self.groupBox_11.setObjectName("groupBox_11")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_11)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_26 = QtWidgets.QLabel(self.groupBox_11)
        self.label_26.setObjectName("label_26")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.motioncor_timeout = QtWidgets.QLineEdit(self.groupBox_11)
        self.motioncor_timeout.setObjectName("motioncor_timeout")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.motioncor_timeout)
        self.label_64 = QtWidgets.QLabel(self.groupBox_11)
        self.label_64.setObjectName("label_64")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_64)
        self.motioncor_trials = QtWidgets.QLineEdit(self.groupBox_11)
        self.motioncor_trials.setObjectName("motioncor_trials")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.motioncor_trials)
        self.groupBox = QtWidgets.QGroupBox(self.Motioncor)
        self.groupBox.setGeometry(QtCore.QRect(510, 10, 171, 210))
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        self.label_25.setObjectName("label_25")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.motioncor_Align = QtWidgets.QLineEdit(self.groupBox)
        self.motioncor_Align.setObjectName("motioncor_Align")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.motioncor_Align)
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setObjectName("label_20")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.motioncor_Trunc = QtWidgets.QLineEdit(self.groupBox)
        self.motioncor_Trunc.setObjectName("motioncor_Trunc")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.motioncor_Trunc)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.motioncor_Tol = QtWidgets.QLineEdit(self.groupBox)
        self.motioncor_Tol.setObjectName("motioncor_Tol")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.motioncor_Tol)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.motioncor_Bft = QtWidgets.QLineEdit(self.groupBox)
        self.motioncor_Bft.setObjectName("motioncor_Bft")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.motioncor_Bft)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.motioncor_StackZ = QtWidgets.QLineEdit(self.groupBox)
        self.motioncor_StackZ.setObjectName("motioncor_StackZ")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.motioncor_StackZ)
        self.label_29 = QtWidgets.QLabel(self.groupBox)
        self.label_29.setObjectName("label_29")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.motioncor_Crop = QtWidgets.QLineEdit(self.groupBox)
        self.motioncor_Crop.setObjectName("motioncor_Crop")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.motioncor_Crop)
        self.groupBox_10 = QtWidgets.QGroupBox(self.Motioncor)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 230, 671, 151))
        self.groupBox_10.setObjectName("groupBox_10")
        self.plainTextEdit_motioncor = QtWidgets.QPlainTextEdit(self.groupBox_10)
        self.plainTextEdit_motioncor.setGeometry(QtCore.QRect(0, 20, 671, 131))
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono L")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit_motioncor.setFont(font)
        self.plainTextEdit_motioncor.setObjectName("plainTextEdit_motioncor")
        self.tabWidget.addTab(self.Motioncor, "")
        self.Gctf = QtWidgets.QWidget()
        self.Gctf.setObjectName("Gctf")
        self.groupBox_6 = QtWidgets.QGroupBox(self.Gctf)
        self.groupBox_6.setGeometry(QtCore.QRect(180, 10, 151, 211))
        self.groupBox_6.setObjectName("groupBox_6")
        self.formLayout_5 = QtWidgets.QFormLayout(self.groupBox_6)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_34 = QtWidgets.QLabel(self.groupBox_6)
        self.label_34.setObjectName("label_34")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.gctf_defL = QtWidgets.QLineEdit(self.groupBox_6)
        self.gctf_defL.setObjectName("gctf_defL")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gctf_defL)
        self.label_35 = QtWidgets.QLabel(self.groupBox_6)
        self.label_35.setObjectName("label_35")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.gctf_defH = QtWidgets.QLineEdit(self.groupBox_6)
        self.gctf_defH.setObjectName("gctf_defH")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.gctf_defH)
        self.label_36 = QtWidgets.QLabel(self.groupBox_6)
        self.label_36.setObjectName("label_36")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.gctf_defS = QtWidgets.QLineEdit(self.groupBox_6)
        self.gctf_defS.setObjectName("gctf_defS")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.gctf_defS)
        self.label_37 = QtWidgets.QLabel(self.groupBox_6)
        self.label_37.setObjectName("label_37")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.gctf_astm = QtWidgets.QLineEdit(self.groupBox_6)
        self.gctf_astm.setObjectName("gctf_astm")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.gctf_astm)
        self.groupBox_7 = QtWidgets.QGroupBox(self.Gctf)
        self.groupBox_7.setGeometry(QtCore.QRect(510, 10, 171, 210))
        self.groupBox_7.setObjectName("groupBox_7")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_7)
        self.formLayout.setObjectName("formLayout")
        self.label_40 = QtWidgets.QLabel(self.groupBox_7)
        self.label_40.setObjectName("label_40")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.gctf_resL = QtWidgets.QLineEdit(self.groupBox_7)
        self.gctf_resL.setObjectName("gctf_resL")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gctf_resL)
        self.label_41 = QtWidgets.QLabel(self.groupBox_7)
        self.label_41.setObjectName("label_41")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.gctf_resH = QtWidgets.QLineEdit(self.groupBox_7)
        self.gctf_resH.setObjectName("gctf_resH")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.gctf_resH)
        self.label_49 = QtWidgets.QLabel(self.groupBox_7)
        self.label_49.setObjectName("label_49")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_49)
        self.gctf_Href_bfac = QtWidgets.QLineEdit(self.groupBox_7)
        self.gctf_Href_bfac.setObjectName("gctf_Href_bfac")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.gctf_Href_bfac)
        self.label_46 = QtWidgets.QLabel(self.groupBox_7)
        self.label_46.setObjectName("label_46")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_46)
        self.gctf_do_Hres_ref = QtWidgets.QLineEdit(self.groupBox_7)
        self.gctf_do_Hres_ref.setObjectName("gctf_do_Hres_ref")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.gctf_do_Hres_ref)
        self.label_47 = QtWidgets.QLabel(self.groupBox_7)
        self.label_47.setObjectName("label_47")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_47)
        self.gctf_Href_resL = QtWidgets.QLineEdit(self.groupBox_7)
        self.gctf_Href_resL.setObjectName("gctf_Href_resL")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.gctf_Href_resL)
        self.label_48 = QtWidgets.QLabel(self.groupBox_7)
        self.label_48.setObjectName("label_48")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_48)
        self.gctf_Href_resH = QtWidgets.QLineEdit(self.groupBox_7)
        self.gctf_Href_resH.setObjectName("gctf_Href_resH")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.gctf_Href_resH)
        self.groupBox_5 = QtWidgets.QGroupBox(self.Gctf)
        self.groupBox_5.setGeometry(QtCore.QRect(340, 10, 161, 211))
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayout_7 = QtWidgets.QFormLayout(self.groupBox_5)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_30 = QtWidgets.QLabel(self.groupBox_5)
        self.label_30.setObjectName("label_30")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.gctf_phase_shift_L = QtWidgets.QLineEdit(self.groupBox_5)
        self.gctf_phase_shift_L.setObjectName("gctf_phase_shift_L")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gctf_phase_shift_L)
        self.label_31 = QtWidgets.QLabel(self.groupBox_5)
        self.label_31.setObjectName("label_31")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.gctf_phase_shift_H = QtWidgets.QLineEdit(self.groupBox_5)
        self.gctf_phase_shift_H.setObjectName("gctf_phase_shift_H")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.gctf_phase_shift_H)
        self.label_32 = QtWidgets.QLabel(self.groupBox_5)
        self.label_32.setObjectName("label_32")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.gctf_phase_shift_S = QtWidgets.QLineEdit(self.groupBox_5)
        self.gctf_phase_shift_S.setObjectName("gctf_phase_shift_S")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.gctf_phase_shift_S)
        self.label_33 = QtWidgets.QLabel(self.groupBox_5)
        self.label_33.setObjectName("label_33")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.gctf_phase_shift_T = QtWidgets.QLineEdit(self.groupBox_5)
        self.gctf_phase_shift_T.setObjectName("gctf_phase_shift_T")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.gctf_phase_shift_T)
        self.groupBox_8 = QtWidgets.QGroupBox(self.Gctf)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 10, 161, 121))
        self.groupBox_8.setObjectName("groupBox_8")
        self.formLayout_9 = QtWidgets.QFormLayout(self.groupBox_8)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_38 = QtWidgets.QLabel(self.groupBox_8)
        self.label_38.setObjectName("label_38")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.gctf_timeout = QtWidgets.QLineEdit(self.groupBox_8)
        self.gctf_timeout.setObjectName("gctf_timeout")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gctf_timeout)
        self.label_39 = QtWidgets.QLabel(self.groupBox_8)
        self.label_39.setObjectName("label_39")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.gctf_trials = QtWidgets.QLineEdit(self.groupBox_8)
        self.gctf_trials.setObjectName("gctf_trials")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.gctf_trials)
        self.label_42 = QtWidgets.QLabel(self.groupBox_8)
        self.label_42.setObjectName("label_42")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_42)
        self.gctf_cc_cutoff = QtWidgets.QLineEdit(self.groupBox_8)
        self.gctf_cc_cutoff.setObjectName("gctf_cc_cutoff")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.gctf_cc_cutoff)
        self.groupBox_9 = QtWidgets.QGroupBox(self.Gctf)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 230, 671, 151))
        self.groupBox_9.setObjectName("groupBox_9")
        self.plainTextEdit_gctf = QtWidgets.QPlainTextEdit(self.groupBox_9)
        self.plainTextEdit_gctf.setGeometry(QtCore.QRect(0, 20, 671, 131))
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono L")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit_gctf.setFont(font)
        self.plainTextEdit_gctf.setObjectName("plainTextEdit_gctf")
        self.tabWidget.addTab(self.Gctf, "")
        self.btn_Exit = QtWidgets.QPushButton(Dialog)
        self.btn_Exit.setGeometry(QtCore.QRect(610, 440, 80, 23))
        self.btn_Exit.setObjectName("btn_Exit")
        self.btn_Run = QtWidgets.QPushButton(Dialog)
        self.btn_Run.setGeometry(QtCore.QRect(520, 440, 80, 23))
        self.btn_Run.setObjectName("btn_Run")
        self.tabWidget.raise_()
        self.btn_Exit.raise_()
        self.btn_Run.raise_()

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "MPIApp"))
        self.gridGroupBox.setTitle(_translate("Dialog", "Microscope Parameters"))
        self.line_ac.setPlaceholderText(_translate("Dialog", "0.1"))
        self.line_dose_per_frame.setPlaceholderText(_translate("Dialog", "1"))
        self.label_9.setText(_translate("Dialog", "Spherical Aberration"))
        self.label_6.setText(_translate("Dialog", "Voltage"))
        self.label_8.setText(_translate("Dialog", "Dose per Frame"))
        self.line_cs.setPlaceholderText(_translate("Dialog", "2.62"))
        self.line_apix.setPlaceholderText(_translate("Dialog", "0.53"))
        self.line_kV.setPlaceholderText(_translate("Dialog", "300"))
        self.label_7.setText(_translate("Dialog", "Pixel Size"))
        self.label_60.setText(_translate("Dialog", "kV"))
        self.label_10.setText(_translate("Dialog", "Amplitude Constrast"))
        self.label_61.setText(_translate("Dialog", "A / pix"))
        self.label_62.setText(_translate("Dialog", "e / A²"))
        self.label_63.setText(_translate("Dialog", "mm"))
        self.formGroupBox.setTitle(_translate("Dialog", "Setup Parameters"))
        self.label.setText(_translate("Dialog", "Input Directory"))
        self.btnGain.setText(_translate("Dialog", "Select File"))
        self.label_5.setText(_translate("Dialog", "GPUs"))
        self.radio_tif.setText(_translate("Dialog", "tif"))
        self.radio_mrc.setText(_translate("Dialog", "mrc"))
        self.btnOutputDir.setText(_translate("Dialog", "Select Directory"))
        self.btnInputDir.setText(_translate("Dialog", "Select Directory"))
        self.GPU_0.setText(_translate("Dialog", "0"))
        self.GPU_1.setText(_translate("Dialog", "1"))
        self.GPU_2.setText(_translate("Dialog", "2"))
        self.GPU_3.setText(_translate("Dialog", "3"))
        self.GPU_4.setText(_translate("Dialog", "4"))
        self.GPU_5.setText(_translate("Dialog", "5"))
        self.GPU_6.setText(_translate("Dialog", "6"))
        self.GPU_7.setText(_translate("Dialog", "7"))
        self.GPU_8.setText(_translate("Dialog", "8"))
        self.GPU_9.setText(_translate("Dialog", "9"))
        self.label_4.setText(_translate("Dialog", "File Extension"))
        self.label_3.setText(_translate("Dialog", "Gain Reference"))
        self.label_2.setText(_translate("Dialog", "Output Directory"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Main), _translate("Dialog", "Main"))
        self.groupBox_2.setTitle(_translate("Dialog", "Main parameters"))
        self.label_18.setText(_translate("Dialog", "FmDose"))
        self.label_16.setText(_translate("Dialog", "FtBin"))
        self.label_17.setText(_translate("Dialog", "InitDose"))
        self.label_11.setText(_translate("Dialog", "Patch"))
        self.label_19.setText(_translate("Dialog", "Throw"))
        self.label_28.setText(_translate("Dialog", "Mag"))
        self.groupBox_4.setTitle(_translate("Dialog", "GroupBox"))
        self.label_12.setText(_translate("Dialog", "Iter"))
        self.label_27.setText(_translate("Dialog", "Tilt"))
        self.label_21.setText(_translate("Dialog", "Group"))
        self.label_22.setText(_translate("Dialog", "FmRef"))
        self.label_23.setText(_translate("Dialog", "RotGain"))
        self.label_24.setText(_translate("Dialog", "FlipGain"))
        self.groupBox_11.setTitle(_translate("Dialog", "Setup"))
        self.label_26.setText(_translate("Dialog", "Timeout"))
        self.motioncor_timeout.setText(_translate("Dialog", "300"))
        self.label_64.setText(_translate("Dialog", "Trials"))
        self.motioncor_trials.setText(_translate("Dialog", "3"))
        self.groupBox.setTitle(_translate("Dialog", "GroupBox"))
        self.label_25.setText(_translate("Dialog", "Align"))
        self.label_20.setText(_translate("Dialog", "Trunc"))
        self.label_13.setText(_translate("Dialog", "Tol"))
        self.label_14.setText(_translate("Dialog", "Bft"))
        self.label_15.setText(_translate("Dialog", "StackZ"))
        self.label_29.setText(_translate("Dialog", "Crop"))
        self.groupBox_10.setTitle(_translate("Dialog", "Additional parameters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Motioncor), _translate("Dialog", "Motioncor"))
        self.groupBox_6.setTitle(_translate("Dialog", "Defocus parameters"))
        self.label_34.setText(_translate("Dialog", "defL"))
        self.label_35.setText(_translate("Dialog", "defH"))
        self.label_36.setText(_translate("Dialog", "defS"))
        self.label_37.setText(_translate("Dialog", "astm"))
        self.groupBox_7.setTitle(_translate("Dialog", "Resolution parameters"))
        self.label_40.setText(_translate("Dialog", "resL"))
        self.label_41.setText(_translate("Dialog", "resH"))
        self.label_49.setText(_translate("Dialog", "Href_bfac"))
        self.label_46.setText(_translate("Dialog", "do_Hres_ref"))
        self.label_47.setText(_translate("Dialog", "Href_resL"))
        self.label_48.setText(_translate("Dialog", "Href_resH"))
        self.groupBox_5.setTitle(_translate("Dialog", "Phase plate parameters"))
        self.label_30.setText(_translate("Dialog", "phase_shift_L"))
        self.label_31.setText(_translate("Dialog", "phase_shift_H"))
        self.label_32.setText(_translate("Dialog", "phase_shift_S"))
        self.label_33.setText(_translate("Dialog", "phase_shift_T"))
        self.groupBox_8.setTitle(_translate("Dialog", "Setup"))
        self.label_38.setText(_translate("Dialog", "Timeout"))
        self.label_39.setText(_translate("Dialog", "Trials"))
        self.label_42.setText(_translate("Dialog", "CC Cutoff"))
        self.groupBox_9.setTitle(_translate("Dialog", "Additional parameters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Gctf), _translate("Dialog", "Gctf"))
        self.btn_Exit.setText(_translate("Dialog", "Exit"))
        self.btn_Run.setText(_translate("Dialog", "Run"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

