# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(709, 467)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(9, 9, 691, 426))
        self.tabWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tabWidget.setObjectName("tabWidget")
        self.Main = QtWidgets.QWidget()
        self.Main.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Main.setObjectName("Main")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Main)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridGroupBox = QtWidgets.QGroupBox(self.Main)
        self.gridGroupBox.setFlat(False)
        self.gridGroupBox.setCheckable(False)
        self.gridGroupBox.setObjectName("gridGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridGroupBox)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_ac = QtWidgets.QLineEdit(self.gridGroupBox)
        self.line_ac.setObjectName("line_ac")
        self.gridLayout_2.addWidget(self.line_ac, 4, 1, 1, 1)
        self.line_dose_per_frame = QtWidgets.QLineEdit(self.gridGroupBox)
        self.line_dose_per_frame.setObjectName("line_dose_per_frame")
        self.gridLayout_2.addWidget(self.line_dose_per_frame, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.line_cs = QtWidgets.QLineEdit(self.gridGroupBox)
        self.line_cs.setObjectName("line_cs")
        self.gridLayout_2.addWidget(self.line_cs, 3, 1, 1, 1)
        self.line_apix = QtWidgets.QLineEdit(self.gridGroupBox)
        self.line_apix.setObjectName("line_apix")
        self.gridLayout_2.addWidget(self.line_apix, 1, 1, 1, 1)
        self.line_kV = QtWidgets.QLineEdit(self.gridGroupBox)
        self.line_kV.setEnabled(True)
        self.line_kV.setInputMethodHints(QtCore.Qt.ImhNone)
        self.line_kV.setObjectName("line_kV")
        self.gridLayout_2.addWidget(self.line_kV, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_60.setObjectName("label_60")
        self.gridLayout_2.addWidget(self.label_60, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_61.setObjectName("label_61")
        self.gridLayout_2.addWidget(self.label_61, 1, 2, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_62.setObjectName("label_62")
        self.gridLayout_2.addWidget(self.label_62, 2, 2, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_63.setObjectName("label_63")
        self.gridLayout_2.addWidget(self.label_63, 3, 2, 1, 1)
        self.gridLayout_4.addWidget(self.gridGroupBox, 2, 0, 1, 1)
        self.formGroupBox = QtWidgets.QGroupBox(self.Main)
        self.formGroupBox.setObjectName("formGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.formGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.formGroupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.btnGain = QtWidgets.QPushButton(self.formGroupBox)
        self.btnGain.setObjectName("btnGain")
        self.gridLayout.addWidget(self.btnGain, 4, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.formGroupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radio_tif = QtWidgets.QRadioButton(self.formGroupBox)
        self.radio_tif.setObjectName("radio_tif")
        self.horizontalLayout.addWidget(self.radio_tif)
        self.radio_mrc = QtWidgets.QRadioButton(self.formGroupBox)
        self.radio_mrc.setObjectName("radio_mrc")
        self.horizontalLayout.addWidget(self.radio_mrc)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 1, 1, 1)
        self.line_Gain = QtWidgets.QLineEdit(self.formGroupBox)
        self.line_Gain.setObjectName("line_Gain")
        self.gridLayout.addWidget(self.line_Gain, 4, 1, 1, 1)
        self.line_OutputDir = QtWidgets.QLineEdit(self.formGroupBox)
        self.line_OutputDir.setObjectName("line_OutputDir")
        self.gridLayout.addWidget(self.line_OutputDir, 3, 1, 1, 1)
        self.btnOutputDir = QtWidgets.QPushButton(self.formGroupBox)
        self.btnOutputDir.setObjectName("btnOutputDir")
        self.gridLayout.addWidget(self.btnOutputDir, 3, 2, 1, 1)
        self.btnInputDir = QtWidgets.QPushButton(self.formGroupBox)
        self.btnInputDir.setObjectName("btnInputDir")
        self.gridLayout.addWidget(self.btnInputDir, 2, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.GPU_0 = QtWidgets.QCheckBox(self.formGroupBox)
        self.GPU_0.setObjectName("GPU_0")
        self.horizontalLayout_2.addWidget(self.GPU_0)
        self.GPU_1 = QtWidgets.QCheckBox(self.formGroupBox)
        self.GPU_1.setObjectName("GPU_1")
        self.horizontalLayout_2.addWidget(self.GPU_1)
        self.GPU_2 = QtWidgets.QCheckBox(self.formGroupBox)
        self.GPU_2.setObjectName("GPU_2")
        self.horizontalLayout_2.addWidget(self.GPU_2)
        self.GPU_3 = QtWidgets.QCheckBox(self.formGroupBox)
        self.GPU_3.setObjectName("GPU_3")
        self.horizontalLayout_2.addWidget(self.GPU_3)
        self.GPU_4 = QtWidgets.QCheckBox(self.formGroupBox)
        self.GPU_4.setObjectName("GPU_4")
        self.horizontalLayout_2.addWidget(self.GPU_4)
        self.GPU_5 = QtWidgets.QCheckBox(self.formGroupBox)
        self.GPU_5.setObjectName("GPU_5")
        self.horizontalLayout_2.addWidget(self.GPU_5)
        self.GPU_6 = QtWidgets.QCheckBox(self.formGroupBox)
        self.GPU_6.setObjectName("GPU_6")
        self.horizontalLayout_2.addWidget(self.GPU_6)
        self.GPU_7 = QtWidgets.QCheckBox(self.formGroupBox)
        self.GPU_7.setObjectName("GPU_7")
        self.horizontalLayout_2.addWidget(self.GPU_7)
        self.GPU_8 = QtWidgets.QCheckBox(self.formGroupBox)
        self.GPU_8.setObjectName("GPU_8")
        self.horizontalLayout_2.addWidget(self.GPU_8)
        self.GPU_9 = QtWidgets.QCheckBox(self.formGroupBox)
        self.GPU_9.setObjectName("GPU_9")
        self.horizontalLayout_2.addWidget(self.GPU_9)
        self.gridLayout.addLayout(self.horizontalLayout_2, 6, 1, 1, 1)
        self.line_InputDir = QtWidgets.QLineEdit(self.formGroupBox)
        self.line_InputDir.setObjectName("line_InputDir")
        self.gridLayout.addWidget(self.line_InputDir, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.formGroupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.formGroupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.formGroupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.formGroupBox, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.Main)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 1, 0, 1, 1)
        self.tabWidget.addTab(self.Main, "")
        self.Motioncor = QtWidgets.QWidget()
        self.Motioncor.setObjectName("Motioncor")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.Motioncor)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.Motioncor)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.motioncor_FtBin = QtWidgets.QLineEdit(self.groupBox_2)
        self.motioncor_FtBin.setObjectName("motioncor_FtBin")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.motioncor_FtBin)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.motioncor_InitDose = QtWidgets.QLineEdit(self.groupBox_2)
        self.motioncor_InitDose.setObjectName("motioncor_InitDose")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.motioncor_InitDose)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.motioncor_FmDose = QtWidgets.QLineEdit(self.groupBox_2)
        self.motioncor_FmDose.setObjectName("motioncor_FmDose")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.motioncor_FmDose)
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.motioncor_Throw = QtWidgets.QLineEdit(self.groupBox_2)
        self.motioncor_Throw.setObjectName("motioncor_Throw")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.motioncor_Throw)
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setObjectName("label_20")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.motioncor_Trunc = QtWidgets.QLineEdit(self.groupBox_2)
        self.motioncor_Trunc.setObjectName("motioncor_Trunc")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.motioncor_Trunc)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.Motioncor)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.motioncor_Patch = QtWidgets.QLineEdit(self.groupBox)
        self.motioncor_Patch.setPlaceholderText("")
        self.motioncor_Patch.setObjectName("motioncor_Patch")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.motioncor_Patch)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.motioncor_Iter = QtWidgets.QLineEdit(self.groupBox)
        self.motioncor_Iter.setPlaceholderText("")
        self.motioncor_Iter.setObjectName("motioncor_Iter")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.motioncor_Iter)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.motioncor_Tol = QtWidgets.QLineEdit(self.groupBox)
        self.motioncor_Tol.setObjectName("motioncor_Tol")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.motioncor_Tol)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.motioncor_Bft = QtWidgets.QLineEdit(self.groupBox)
        self.motioncor_Bft.setObjectName("motioncor_Bft")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.motioncor_Bft)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.motioncor_StackZ = QtWidgets.QLineEdit(self.groupBox)
        self.motioncor_StackZ.setObjectName("motioncor_StackZ")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.motioncor_StackZ)
        self.gridLayout_3.addWidget(self.groupBox, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.Motioncor)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_8 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setObjectName("label_21")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.motioncor_Group = QtWidgets.QLineEdit(self.groupBox_4)
        self.motioncor_Group.setObjectName("motioncor_Group")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.motioncor_Group)
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setObjectName("label_22")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.motioncor_FmRef = QtWidgets.QLineEdit(self.groupBox_4)
        self.motioncor_FmRef.setObjectName("motioncor_FmRef")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.motioncor_FmRef)
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setObjectName("label_23")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.motioncor_RotGain = QtWidgets.QLineEdit(self.groupBox_4)
        self.motioncor_RotGain.setObjectName("motioncor_RotGain")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.motioncor_RotGain)
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setObjectName("label_24")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.motioncor_FlipGain = QtWidgets.QLineEdit(self.groupBox_4)
        self.motioncor_FlipGain.setObjectName("motioncor_FlipGain")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.motioncor_FlipGain)
        self.label_25 = QtWidgets.QLabel(self.groupBox_4)
        self.label_25.setObjectName("label_25")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.motioncor_Align = QtWidgets.QLineEdit(self.groupBox_4)
        self.motioncor_Align.setObjectName("motioncor_Align")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.motioncor_Align)
        self.gridLayout_5.addWidget(self.groupBox_4, 0, 2, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.Motioncor)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_6 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_27 = QtWidgets.QLabel(self.groupBox_3)
        self.label_27.setObjectName("label_27")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.motioncor_Tilt = QtWidgets.QLineEdit(self.groupBox_3)
        self.motioncor_Tilt.setObjectName("motioncor_Tilt")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.motioncor_Tilt)
        self.label_28 = QtWidgets.QLabel(self.groupBox_3)
        self.label_28.setObjectName("label_28")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.motioncor_Mag = QtWidgets.QLineEdit(self.groupBox_3)
        self.motioncor_Mag.setObjectName("motioncor_Mag")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.motioncor_Mag)
        self.label_29 = QtWidgets.QLabel(self.groupBox_3)
        self.label_29.setObjectName("label_29")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.motioncor_Crop = QtWidgets.QLineEdit(self.groupBox_3)
        self.motioncor_Crop.setObjectName("motioncor_Crop")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.motioncor_Crop)
        self.gridLayout_5.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.Motioncor)
        self.groupBox_11.setObjectName("groupBox_11")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_11)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_26 = QtWidgets.QLabel(self.groupBox_11)
        self.label_26.setObjectName("label_26")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.label_64 = QtWidgets.QLabel(self.groupBox_11)
        self.label_64.setObjectName("label_64")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_64)
        self.motioncor_timeout = QtWidgets.QLineEdit(self.groupBox_11)
        self.motioncor_timeout.setObjectName("motioncor_timeout")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.motioncor_timeout)
        self.motioncor_trials = QtWidgets.QLineEdit(self.groupBox_11)
        self.motioncor_trials.setObjectName("motioncor_trials")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.motioncor_trials)
        self.gridLayout_5.addWidget(self.groupBox_11, 1, 1, 1, 1)
        self.tabWidget.addTab(self.Motioncor, "")
        self.Gctf = QtWidgets.QWidget()
        self.Gctf.setObjectName("Gctf")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Gctf)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_6 = QtWidgets.QGroupBox(self.Gctf)
        self.groupBox_6.setObjectName("groupBox_6")
        self.formLayout_11 = QtWidgets.QFormLayout(self.groupBox_6)
        self.formLayout_11.setObjectName("formLayout_11")
        self.label_34 = QtWidgets.QLabel(self.groupBox_6)
        self.label_34.setObjectName("label_34")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_38)
        self.label_35 = QtWidgets.QLabel(self.groupBox_6)
        self.label_35.setObjectName("label_35")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_39)
        self.label_36 = QtWidgets.QLabel(self.groupBox_6)
        self.label_36.setObjectName("label_36")
        self.formLayout_11.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.formLayout_11.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_40)
        self.label_37 = QtWidgets.QLabel(self.groupBox_6)
        self.label_37.setObjectName("label_37")
        self.formLayout_11.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.formLayout_11.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_41)
        self.gridLayout_7.addWidget(self.groupBox_6, 0, 1, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_5 = QtWidgets.QGroupBox(self.Gctf)
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayout_9 = QtWidgets.QFormLayout(self.groupBox_5)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_30 = QtWidgets.QLabel(self.groupBox_5)
        self.label_30.setObjectName("label_30")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_28)
        self.label_31 = QtWidgets.QLabel(self.groupBox_5)
        self.label_31.setObjectName("label_31")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_29)
        self.label_32 = QtWidgets.QLabel(self.groupBox_5)
        self.label_32.setObjectName("label_32")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_30)
        self.label_33 = QtWidgets.QLabel(self.groupBox_5)
        self.label_33.setObjectName("label_33")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_31)
        self.gridLayout_6.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.Gctf)
        self.groupBox_7.setObjectName("groupBox_7")
        self.formLayout_13 = QtWidgets.QFormLayout(self.groupBox_7)
        self.formLayout_13.setObjectName("formLayout_13")
        self.label_38 = QtWidgets.QLabel(self.groupBox_7)
        self.label_38.setObjectName("label_38")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_32.setReadOnly(False)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_32)
        self.label_39 = QtWidgets.QLabel(self.groupBox_7)
        self.label_39.setObjectName("label_39")
        self.formLayout_13.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.formLayout_13.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_33)
        self.label_40 = QtWidgets.QLabel(self.groupBox_7)
        self.label_40.setObjectName("label_40")
        self.formLayout_13.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.formLayout_13.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_34)
        self.label_41 = QtWidgets.QLabel(self.groupBox_7)
        self.label_41.setObjectName("label_41")
        self.formLayout_13.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.formLayout_13.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_35)
        self.label_42 = QtWidgets.QLabel(self.groupBox_7)
        self.label_42.setObjectName("label_42")
        self.formLayout_13.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_42)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.formLayout_13.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_36)
        self.label_50 = QtWidgets.QLabel(self.groupBox_7)
        self.label_50.setObjectName("label_50")
        self.formLayout_13.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_50)
        self.label_51 = QtWidgets.QLabel(self.groupBox_7)
        self.label_51.setObjectName("label_51")
        self.formLayout_13.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_51)
        self.gridLayout_7.addWidget(self.groupBox_7, 0, 2, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.Gctf)
        self.groupBox_9.setObjectName("groupBox_9")
        self.formLayout_17 = QtWidgets.QFormLayout(self.groupBox_9)
        self.formLayout_17.setObjectName("formLayout_17")
        self.label_45 = QtWidgets.QLabel(self.groupBox_9)
        self.label_45.setObjectName("label_45")
        self.formLayout_17.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_45)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.formLayout_17.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_44)
        self.label_44 = QtWidgets.QLabel(self.groupBox_9)
        self.label_44.setObjectName("label_44")
        self.formLayout_17.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_44)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.formLayout_17.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_43)
        self.label_46 = QtWidgets.QLabel(self.groupBox_9)
        self.label_46.setObjectName("label_46")
        self.formLayout_17.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_46)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.formLayout_17.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_42)
        self.label_47 = QtWidgets.QLabel(self.groupBox_9)
        self.label_47.setObjectName("label_47")
        self.formLayout_17.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_47)
        self.lineEdit_45 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.formLayout_17.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_45)
        self.label_48 = QtWidgets.QLabel(self.groupBox_9)
        self.label_48.setObjectName("label_48")
        self.formLayout_17.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_48)
        self.lineEdit_46 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.formLayout_17.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_46)
        self.label_49 = QtWidgets.QLabel(self.groupBox_9)
        self.label_49.setObjectName("label_49")
        self.formLayout_17.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_49)
        self.lineEdit_47 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.formLayout_17.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_47)
        self.gridLayout_7.addWidget(self.groupBox_9, 0, 3, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.Gctf)
        self.groupBox_8.setObjectName("groupBox_8")
        self.formLayout_15 = QtWidgets.QFormLayout(self.groupBox_8)
        self.formLayout_15.setObjectName("formLayout_15")
        self.label_43 = QtWidgets.QLabel(self.groupBox_8)
        self.label_43.setObjectName("label_43")
        self.formLayout_15.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_43)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.formLayout_15.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_37)
        self.label_52 = QtWidgets.QLabel(self.groupBox_8)
        self.label_52.setObjectName("label_52")
        self.formLayout_15.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_52)
        self.gridLayout_7.addWidget(self.groupBox_8, 1, 0, 1, 1)
        self.tabWidget.addTab(self.Gctf, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_10.setGeometry(QtCore.QRect(120, 50, 371, 161))
        self.groupBox_10.setAutoFillBackground(False)
        self.groupBox_10.setObjectName("groupBox_10")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_10)
        self.scrollArea.setGeometry(QtCore.QRect(0, 20, 371, 141))
        self.scrollArea.setAutoFillBackground(True)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 355, 215))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout_10 = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout_10.setContentsMargins(0, 0, 0, 0)
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_55 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_55.setObjectName("label_55")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_55)
        self.label_54 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_54.setObjectName("label_54")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_54)
        self.label_53 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_53.setObjectName("label_53")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_53)
        self.label_56 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_56.setObjectName("label_56")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_56)
        self.label_57 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_57.setObjectName("label_57")
        self.formLayout_10.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_57)
        self.label_58 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_58.setObjectName("label_58")
        self.formLayout_10.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_58)
        self.label_59 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_59.setObjectName("label_59")
        self.formLayout_10.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_59)
        self.lineEdit_48 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_48)
        self.lineEdit_49 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_49)
        self.lineEdit_50 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_50)
        self.lineEdit_51 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_51)
        self.lineEdit_52 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.formLayout_10.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_52)
        self.lineEdit_53 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.formLayout_10.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_53)
        self.lineEdit_54 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.formLayout_10.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_54)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.tab, "")
        self.btn_Exit = QtWidgets.QPushButton(Dialog)
        self.btn_Exit.setGeometry(QtCore.QRect(610, 440, 80, 23))
        self.btn_Exit.setObjectName("btn_Exit")
        self.btn_Run = QtWidgets.QPushButton(Dialog)
        self.btn_Run.setGeometry(QtCore.QRect(520, 440, 80, 23))
        self.btn_Run.setObjectName("btn_Run")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.gridGroupBox.setTitle(_translate("Dialog", "Microscope Parameters"))
        self.line_ac.setPlaceholderText(_translate("Dialog", "0.1"))
        self.line_dose_per_frame.setPlaceholderText(_translate("Dialog", "1"))
        self.label_9.setText(_translate("Dialog", "Spherical Aberration"))
        self.label_6.setText(_translate("Dialog", "Voltage"))
        self.label_8.setText(_translate("Dialog", "Dose per Frame"))
        self.line_cs.setPlaceholderText(_translate("Dialog", "2.62"))
        self.line_apix.setPlaceholderText(_translate("Dialog", "0.53"))
        self.line_kV.setPlaceholderText(_translate("Dialog", "300"))
        self.label_7.setText(_translate("Dialog", "Pixel Size"))
        self.label_60.setText(_translate("Dialog", "kV"))
        self.label_10.setText(_translate("Dialog", "Amplitude Constrast"))
        self.label_61.setText(_translate("Dialog", "A / pix"))
        self.label_62.setText(_translate("Dialog", "e / A²"))
        self.label_63.setText(_translate("Dialog", "mm"))
        self.formGroupBox.setTitle(_translate("Dialog", "Setup Parameters"))
        self.label.setText(_translate("Dialog", "Input Directory"))
        self.btnGain.setText(_translate("Dialog", "Select File"))
        self.label_5.setText(_translate("Dialog", "GPUs"))
        self.radio_tif.setText(_translate("Dialog", "tif"))
        self.radio_mrc.setText(_translate("Dialog", "mrc"))
        self.btnOutputDir.setText(_translate("Dialog", "Select Directory"))
        self.btnInputDir.setText(_translate("Dialog", "Select Directory"))
        self.GPU_0.setText(_translate("Dialog", "0"))
        self.GPU_1.setText(_translate("Dialog", "1"))
        self.GPU_2.setText(_translate("Dialog", "2"))
        self.GPU_3.setText(_translate("Dialog", "3"))
        self.GPU_4.setText(_translate("Dialog", "4"))
        self.GPU_5.setText(_translate("Dialog", "5"))
        self.GPU_6.setText(_translate("Dialog", "6"))
        self.GPU_7.setText(_translate("Dialog", "7"))
        self.GPU_8.setText(_translate("Dialog", "8"))
        self.GPU_9.setText(_translate("Dialog", "9"))
        self.label_4.setText(_translate("Dialog", "File Extension"))
        self.label_3.setText(_translate("Dialog", "Gain Reference"))
        self.label_2.setText(_translate("Dialog", "Output Directory"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Main), _translate("Dialog", "Main"))
        self.groupBox_2.setTitle(_translate("Dialog", "GroupBox"))
        self.label_16.setText(_translate("Dialog", "FtBin"))
        self.label_17.setText(_translate("Dialog", "InitDose"))
        self.label_18.setText(_translate("Dialog", "FmDose"))
        self.label_19.setText(_translate("Dialog", "Throw"))
        self.label_20.setText(_translate("Dialog", "Trunc"))
        self.groupBox.setTitle(_translate("Dialog", "GroupBox"))
        self.label_11.setText(_translate("Dialog", "Patch"))
        self.label_12.setText(_translate("Dialog", "Iter"))
        self.label_13.setText(_translate("Dialog", "Tol"))
        self.label_14.setText(_translate("Dialog", "Bft"))
        self.label_15.setText(_translate("Dialog", "StackZ"))
        self.groupBox_4.setTitle(_translate("Dialog", "GroupBox"))
        self.label_21.setText(_translate("Dialog", "Group"))
        self.label_22.setText(_translate("Dialog", "FmRef"))
        self.label_23.setText(_translate("Dialog", "RotGain"))
        self.label_24.setText(_translate("Dialog", "FlipGain"))
        self.label_25.setText(_translate("Dialog", "Align"))
        self.groupBox_3.setTitle(_translate("Dialog", "GroupBox"))
        self.label_27.setText(_translate("Dialog", "Tilt"))
        self.label_28.setText(_translate("Dialog", "Mag"))
        self.label_29.setText(_translate("Dialog", "Crop"))
        self.groupBox_11.setTitle(_translate("Dialog", "Processing Parameters"))
        self.label_26.setText(_translate("Dialog", "Timeout"))
        self.label_64.setText(_translate("Dialog", "Trials"))
        self.motioncor_timeout.setText(_translate("Dialog", "300"))
        self.motioncor_trials.setText(_translate("Dialog", "3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Motioncor), _translate("Dialog", "Motioncor"))
        self.groupBox_6.setTitle(_translate("Dialog", "Defocus parameters"))
        self.label_34.setText(_translate("Dialog", "defL"))
        self.label_35.setText(_translate("Dialog", "defH"))
        self.label_36.setText(_translate("Dialog", "defS"))
        self.label_37.setText(_translate("Dialog", "astm"))
        self.groupBox_5.setTitle(_translate("Dialog", "Phase plate parameters"))
        self.label_30.setText(_translate("Dialog", "phase_shift_L"))
        self.label_31.setText(_translate("Dialog", "phase_shift_H"))
        self.label_32.setText(_translate("Dialog", "phase_shift_S"))
        self.label_33.setText(_translate("Dialog", "phase_shift_T"))
        self.groupBox_7.setTitle(_translate("Dialog", "GroupBox"))
        self.label_38.setText(_translate("Dialog", "dstep"))
        self.lineEdit_32.setText(_translate("Dialog", "test"))
        self.label_39.setText(_translate("Dialog", "bfac"))
        self.label_40.setText(_translate("Dialog", "resL"))
        self.label_41.setText(_translate("Dialog", "resH"))
        self.label_42.setText(_translate("Dialog", "boxsize"))
        self.label_50.setText(_translate("Dialog", "B_resL"))
        self.label_51.setText(_translate("Dialog", "B_resH"))
        self.groupBox_9.setTitle(_translate("Dialog", "GroupBox"))
        self.label_45.setText(_translate("Dialog", "convsize"))
        self.label_44.setText(_translate("Dialog", "overlap"))
        self.label_46.setText(_translate("Dialog", "do_Hres_ref"))
        self.label_47.setText(_translate("Dialog", "Href_resL"))
        self.label_48.setText(_translate("Dialog", "Href_resH"))
        self.label_49.setText(_translate("Dialog", "Href_bfac"))
        self.groupBox_8.setTitle(_translate("Dialog", "Defaults"))
        self.label_43.setText(_translate("Dialog", "do_EPA"))
        self.lineEdit_37.setText(_translate("Dialog", "True"))
        self.label_52.setText(_translate("Dialog", "do_mdef_refine"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Gctf), _translate("Dialog", "Gctf"))
        self.groupBox_10.setTitle(_translate("Dialog", "GroupBox"))
        self.label_55.setText(_translate("Dialog", "TextLabel"))
        self.label_54.setText(_translate("Dialog", "TextLabel"))
        self.label_53.setText(_translate("Dialog", "TextLabel"))
        self.label_56.setText(_translate("Dialog", "TextLabel"))
        self.label_57.setText(_translate("Dialog", "TextLabel"))
        self.label_58.setText(_translate("Dialog", "TextLabel"))
        self.label_59.setText(_translate("Dialog", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Page"))
        self.btn_Exit.setText(_translate("Dialog", "Exit"))
        self.btn_Run.setText(_translate("Dialog", "Run"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

