# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(745, 524)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_Exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Exit.setObjectName("btn_Exit")
        self.gridLayout_3.addWidget(self.btn_Exit, 1, 4, 1, 1)
        self.btn_Run = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Run.setObjectName("btn_Run")
        self.gridLayout_3.addWidget(self.btn_Run, 1, 3, 1, 1)
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_status.setFont(font)
        self.label_status.setText("")
        self.label_status.setObjectName("label_status")
        self.gridLayout_3.addWidget(self.label_status, 1, 1, 1, 2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tabWidget.setObjectName("tabWidget")
        self.Main = QtWidgets.QWidget()
        self.Main.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Main.setObjectName("Main")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Main)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_Main_1 = QtWidgets.QGroupBox(self.Main)
        self.groupBox_Main_1.setObjectName("groupBox_Main_1")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_Main_1)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_Main_1)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.btnGain = QtWidgets.QPushButton(self.groupBox_Main_1)
        self.btnGain.setObjectName("btnGain")
        self.gridLayout.addWidget(self.btnGain, 4, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_Main_1)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radio_tif = QtWidgets.QRadioButton(self.groupBox_Main_1)
        self.radio_tif.setChecked(True)
        self.radio_tif.setObjectName("radio_tif")
        self.horizontalLayout.addWidget(self.radio_tif)
        self.radio_mrc = QtWidgets.QRadioButton(self.groupBox_Main_1)
        self.radio_mrc.setObjectName("radio_mrc")
        self.horizontalLayout.addWidget(self.radio_mrc)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 1, 1, 1)
        self.line_Gain = QtWidgets.QLineEdit(self.groupBox_Main_1)
        self.line_Gain.setObjectName("line_Gain")
        self.gridLayout.addWidget(self.line_Gain, 4, 1, 1, 1)
        self.line_OutputDir = QtWidgets.QLineEdit(self.groupBox_Main_1)
        self.line_OutputDir.setObjectName("line_OutputDir")
        self.gridLayout.addWidget(self.line_OutputDir, 3, 1, 1, 1)
        self.btnOutputDir = QtWidgets.QPushButton(self.groupBox_Main_1)
        self.btnOutputDir.setObjectName("btnOutputDir")
        self.gridLayout.addWidget(self.btnOutputDir, 3, 2, 1, 1)
        self.btnInputDir = QtWidgets.QPushButton(self.groupBox_Main_1)
        self.btnInputDir.setObjectName("btnInputDir")
        self.gridLayout.addWidget(self.btnInputDir, 2, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.GPU_0 = QtWidgets.QCheckBox(self.groupBox_Main_1)
        self.GPU_0.setChecked(False)
        self.GPU_0.setObjectName("GPU_0")
        self.horizontalLayout_2.addWidget(self.GPU_0)
        self.GPU_1 = QtWidgets.QCheckBox(self.groupBox_Main_1)
        self.GPU_1.setObjectName("GPU_1")
        self.horizontalLayout_2.addWidget(self.GPU_1)
        self.GPU_2 = QtWidgets.QCheckBox(self.groupBox_Main_1)
        self.GPU_2.setObjectName("GPU_2")
        self.horizontalLayout_2.addWidget(self.GPU_2)
        self.GPU_3 = QtWidgets.QCheckBox(self.groupBox_Main_1)
        self.GPU_3.setObjectName("GPU_3")
        self.horizontalLayout_2.addWidget(self.GPU_3)
        self.GPU_4 = QtWidgets.QCheckBox(self.groupBox_Main_1)
        self.GPU_4.setObjectName("GPU_4")
        self.horizontalLayout_2.addWidget(self.GPU_4)
        self.GPU_5 = QtWidgets.QCheckBox(self.groupBox_Main_1)
        self.GPU_5.setObjectName("GPU_5")
        self.horizontalLayout_2.addWidget(self.GPU_5)
        self.GPU_6 = QtWidgets.QCheckBox(self.groupBox_Main_1)
        self.GPU_6.setObjectName("GPU_6")
        self.horizontalLayout_2.addWidget(self.GPU_6)
        self.GPU_7 = QtWidgets.QCheckBox(self.groupBox_Main_1)
        self.GPU_7.setObjectName("GPU_7")
        self.horizontalLayout_2.addWidget(self.GPU_7)
        self.GPU_8 = QtWidgets.QCheckBox(self.groupBox_Main_1)
        self.GPU_8.setObjectName("GPU_8")
        self.horizontalLayout_2.addWidget(self.GPU_8)
        self.GPU_9 = QtWidgets.QCheckBox(self.groupBox_Main_1)
        self.GPU_9.setObjectName("GPU_9")
        self.horizontalLayout_2.addWidget(self.GPU_9)
        self.gridLayout.addLayout(self.horizontalLayout_2, 6, 1, 1, 1)
        self.line_InputDir = QtWidgets.QLineEdit(self.groupBox_Main_1)
        self.line_InputDir.setObjectName("line_InputDir")
        self.gridLayout.addWidget(self.line_InputDir, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_Main_1)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_Main_1)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_Main_1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_Main_1, 0, 0, 1, 2)
        self.groupBox_Main_2 = QtWidgets.QGroupBox(self.Main)
        self.groupBox_Main_2.setFlat(False)
        self.groupBox_Main_2.setCheckable(False)
        self.groupBox_Main_2.setObjectName("groupBox_Main_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_Main_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox_Main_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_Main_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.line_kV = QtWidgets.QLineEdit(self.groupBox_Main_2)
        self.line_kV.setEnabled(True)
        self.line_kV.setInputMethodHints(QtCore.Qt.ImhNone)
        self.line_kV.setObjectName("line_kV")
        self.gridLayout_2.addWidget(self.line_kV, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_Main_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.line_cs = QtWidgets.QLineEdit(self.groupBox_Main_2)
        self.line_cs.setObjectName("line_cs")
        self.gridLayout_2.addWidget(self.line_cs, 3, 1, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.groupBox_Main_2)
        self.label_63.setObjectName("label_63")
        self.gridLayout_2.addWidget(self.label_63, 3, 2, 1, 1)
        self.line_dose_per_frame = QtWidgets.QLineEdit(self.groupBox_Main_2)
        self.line_dose_per_frame.setObjectName("line_dose_per_frame")
        self.gridLayout_2.addWidget(self.line_dose_per_frame, 2, 1, 1, 1)
        self.line_ac = QtWidgets.QLineEdit(self.groupBox_Main_2)
        self.line_ac.setObjectName("line_ac")
        self.gridLayout_2.addWidget(self.line_ac, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_Main_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.groupBox_Main_2)
        self.label_60.setObjectName("label_60")
        self.gridLayout_2.addWidget(self.label_60, 0, 2, 1, 1)
        self.line_apix = QtWidgets.QLineEdit(self.groupBox_Main_2)
        self.line_apix.setObjectName("line_apix")
        self.gridLayout_2.addWidget(self.line_apix, 1, 1, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.groupBox_Main_2)
        self.label_61.setObjectName("label_61")
        self.gridLayout_2.addWidget(self.label_61, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_Main_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.groupBox_Main_2)
        self.label_62.setObjectName("label_62")
        self.gridLayout_2.addWidget(self.label_62, 2, 2, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_Main_2, 1, 0, 1, 1)
        self.groupBox_Main_3 = QtWidgets.QGroupBox(self.Main)
        self.groupBox_Main_3.setObjectName("groupBox_Main_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_Main_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.listWidget_Files = QtWidgets.QListWidget(self.groupBox_Main_3)
        self.listWidget_Files.setMinimumSize(QtCore.QSize(300, 0))
        self.listWidget_Files.setObjectName("listWidget_Files")
        self.gridLayout_4.addWidget(self.listWidget_Files, 0, 0, 1, 3)
        self.btn_addFiles = QtWidgets.QToolButton(self.groupBox_Main_3)
        self.btn_addFiles.setStyleSheet("font: 75 14pt \"Noto Sans Cham\";\n"
"color: rgb(0, 170, 0);")
        self.btn_addFiles.setObjectName("btn_addFiles")
        self.gridLayout_4.addWidget(self.btn_addFiles, 1, 0, 1, 1)
        self.btn_removeFiles = QtWidgets.QToolButton(self.groupBox_Main_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_removeFiles.sizePolicy().hasHeightForWidth())
        self.btn_removeFiles.setSizePolicy(sizePolicy)
        self.btn_removeFiles.setMinimumSize(QtCore.QSize(29, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Cham")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btn_removeFiles.setFont(font)
        self.btn_removeFiles.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 75 14pt \"Noto Sans Cham\";")
        self.btn_removeFiles.setObjectName("btn_removeFiles")
        self.gridLayout_4.addWidget(self.btn_removeFiles, 1, 1, 1, 1)
        self.btn_clearAllFiles = QtWidgets.QPushButton(self.groupBox_Main_3)
        self.btn_clearAllFiles.setObjectName("btn_clearAllFiles")
        self.gridLayout_4.addWidget(self.btn_clearAllFiles, 1, 2, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_Main_3, 1, 1, 1, 1)
        self.tabWidget.addTab(self.Main, "")
        self.Motioncor = QtWidgets.QWidget()
        self.Motioncor.setObjectName("Motioncor")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.Motioncor)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_Motioncor_1 = QtWidgets.QGroupBox(self.Motioncor)
        self.groupBox_Motioncor_1.setObjectName("groupBox_Motioncor_1")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_Motioncor_1)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_26 = QtWidgets.QLabel(self.groupBox_Motioncor_1)
        self.label_26.setObjectName("label_26")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.motioncor_timeout = QtWidgets.QLineEdit(self.groupBox_Motioncor_1)
        self.motioncor_timeout.setText("")
        self.motioncor_timeout.setObjectName("motioncor_timeout")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.motioncor_timeout)
        self.label_64 = QtWidgets.QLabel(self.groupBox_Motioncor_1)
        self.label_64.setObjectName("label_64")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_64)
        self.motioncor_trials = QtWidgets.QLineEdit(self.groupBox_Motioncor_1)
        self.motioncor_trials.setToolTip("")
        self.motioncor_trials.setText("")
        self.motioncor_trials.setObjectName("motioncor_trials")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.motioncor_trials)
        self.label_23 = QtWidgets.QLabel(self.groupBox_Motioncor_1)
        self.label_23.setObjectName("label_23")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.btn_motioncor_executable = QtWidgets.QToolButton(self.groupBox_Motioncor_1)
        self.btn_motioncor_executable.setObjectName("btn_motioncor_executable")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btn_motioncor_executable)
        self.gridLayout_5.addWidget(self.groupBox_Motioncor_1, 0, 0, 1, 1)
        self.groupBox_Motioncor_2 = QtWidgets.QGroupBox(self.Motioncor)
        self.groupBox_Motioncor_2.setObjectName("groupBox_Motioncor_2")
        self.formLayout_8 = QtWidgets.QFormLayout(self.groupBox_Motioncor_2)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_18 = QtWidgets.QLabel(self.groupBox_Motioncor_2)
        self.label_18.setObjectName("label_18")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.motioncor_FmDose = QtWidgets.QLineEdit(self.groupBox_Motioncor_2)
        self.motioncor_FmDose.setEnabled(False)
        self.motioncor_FmDose.setAutoFillBackground(False)
        self.motioncor_FmDose.setReadOnly(True)
        self.motioncor_FmDose.setObjectName("motioncor_FmDose")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.motioncor_FmDose)
        self.label_13 = QtWidgets.QLabel(self.groupBox_Motioncor_2)
        self.label_13.setObjectName("label_13")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.motioncor_kV = QtWidgets.QLineEdit(self.groupBox_Motioncor_2)
        self.motioncor_kV.setEnabled(False)
        self.motioncor_kV.setObjectName("motioncor_kV")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.motioncor_kV)
        self.label_15 = QtWidgets.QLabel(self.groupBox_Motioncor_2)
        self.label_15.setObjectName("label_15")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.motioncor_PixSize = QtWidgets.QLineEdit(self.groupBox_Motioncor_2)
        self.motioncor_PixSize.setEnabled(False)
        self.motioncor_PixSize.setObjectName("motioncor_PixSize")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.motioncor_PixSize)
        self.gridLayout_5.addWidget(self.groupBox_Motioncor_2, 0, 1, 1, 1)
        self.groupBox_Motioncor_3 = QtWidgets.QGroupBox(self.Motioncor)
        self.groupBox_Motioncor_3.setObjectName("groupBox_Motioncor_3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_Motioncor_3)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_12 = QtWidgets.QLabel(self.groupBox_Motioncor_3)
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.motioncor_Iter = QtWidgets.QLineEdit(self.groupBox_Motioncor_3)
        self.motioncor_Iter.setPlaceholderText("")
        self.motioncor_Iter.setObjectName("motioncor_Iter")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.motioncor_Iter)
        self.label_17 = QtWidgets.QLabel(self.groupBox_Motioncor_3)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.motioncor_InitDose = QtWidgets.QLineEdit(self.groupBox_Motioncor_3)
        self.motioncor_InitDose.setObjectName("motioncor_InitDose")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.motioncor_InitDose)
        self.label_11 = QtWidgets.QLabel(self.groupBox_Motioncor_3)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.motioncor_Patch = QtWidgets.QLineEdit(self.groupBox_Motioncor_3)
        self.motioncor_Patch.setPlaceholderText("")
        self.motioncor_Patch.setObjectName("motioncor_Patch")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.motioncor_Patch)
        self.label_28 = QtWidgets.QLabel(self.groupBox_Motioncor_3)
        self.label_28.setObjectName("label_28")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.motioncor_Mag = QtWidgets.QLineEdit(self.groupBox_Motioncor_3)
        self.motioncor_Mag.setObjectName("motioncor_Mag")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.motioncor_Mag)
        self.label_16 = QtWidgets.QLabel(self.groupBox_Motioncor_3)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.motioncor_FtBin = QtWidgets.QLineEdit(self.groupBox_Motioncor_3)
        self.motioncor_FtBin.setEnabled(True)
        self.motioncor_FtBin.setObjectName("motioncor_FtBin")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.motioncor_FtBin)
        self.gridLayout_5.addWidget(self.groupBox_Motioncor_3, 0, 2, 1, 1)
        self.groupBox_Motioncor_4 = QtWidgets.QGroupBox(self.Motioncor)
        self.groupBox_Motioncor_4.setObjectName("groupBox_Motioncor_4")
        self.formLayout_6 = QtWidgets.QFormLayout(self.groupBox_Motioncor_4)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_21 = QtWidgets.QLabel(self.groupBox_Motioncor_4)
        self.label_21.setObjectName("label_21")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.motioncor_Group = QtWidgets.QLineEdit(self.groupBox_Motioncor_4)
        self.motioncor_Group.setObjectName("motioncor_Group")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.motioncor_Group)
        self.label_22 = QtWidgets.QLabel(self.groupBox_Motioncor_4)
        self.label_22.setObjectName("label_22")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.motioncor_FmRef = QtWidgets.QLineEdit(self.groupBox_Motioncor_4)
        self.motioncor_FmRef.setObjectName("motioncor_FmRef")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.motioncor_FmRef)
        self.label_14 = QtWidgets.QLabel(self.groupBox_Motioncor_4)
        self.label_14.setObjectName("label_14")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.motioncor_Bft = QtWidgets.QLineEdit(self.groupBox_Motioncor_4)
        self.motioncor_Bft.setObjectName("motioncor_Bft")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.motioncor_Bft)
        self.label_19 = QtWidgets.QLabel(self.groupBox_Motioncor_4)
        self.label_19.setObjectName("label_19")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.motioncor_Throw = QtWidgets.QLineEdit(self.groupBox_Motioncor_4)
        self.motioncor_Throw.setObjectName("motioncor_Throw")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.motioncor_Throw)
        self.label_47 = QtWidgets.QLabel(self.groupBox_Motioncor_4)
        self.label_47.setObjectName("label_47")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_47)
        self.motioncor_Trunc = QtWidgets.QLineEdit(self.groupBox_Motioncor_4)
        self.motioncor_Trunc.setObjectName("motioncor_Trunc")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.motioncor_Trunc)
        self.gridLayout_5.addWidget(self.groupBox_Motioncor_4, 0, 3, 1, 1)
        self.groupBox_Motioncor_5 = QtWidgets.QGroupBox(self.Motioncor)
        self.groupBox_Motioncor_5.setObjectName("groupBox_Motioncor_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_Motioncor_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.plainTextEdit_motioncor = QtWidgets.QPlainTextEdit(self.groupBox_Motioncor_5)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono L")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.plainTextEdit_motioncor.setFont(font)
        self.plainTextEdit_motioncor.setObjectName("plainTextEdit_motioncor")
        self.horizontalLayout_3.addWidget(self.plainTextEdit_motioncor)
        self.gridLayout_5.addWidget(self.groupBox_Motioncor_5, 1, 0, 1, 4)
        self.tabWidget.addTab(self.Motioncor, "")
        self.Gctf = QtWidgets.QWidget()
        self.Gctf.setObjectName("Gctf")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.Gctf)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_Gctf_1 = QtWidgets.QGroupBox(self.Gctf)
        self.groupBox_Gctf_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_Gctf_1.setObjectName("groupBox_Gctf_1")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_Gctf_1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_38 = QtWidgets.QLabel(self.groupBox_Gctf_1)
        self.label_38.setObjectName("label_38")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.gctf_timeout = QtWidgets.QLineEdit(self.groupBox_Gctf_1)
        self.gctf_timeout.setText("")
        self.gctf_timeout.setObjectName("gctf_timeout")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gctf_timeout)
        self.label_39 = QtWidgets.QLabel(self.groupBox_Gctf_1)
        self.label_39.setObjectName("label_39")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.gctf_trials = QtWidgets.QLineEdit(self.groupBox_Gctf_1)
        self.gctf_trials.setText("")
        self.gctf_trials.setObjectName("gctf_trials")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.gctf_trials)
        self.label_42 = QtWidgets.QLabel(self.groupBox_Gctf_1)
        self.label_42.setObjectName("label_42")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_42)
        self.gctf_cc_cutoff = QtWidgets.QLineEdit(self.groupBox_Gctf_1)
        self.gctf_cc_cutoff.setText("")
        self.gctf_cc_cutoff.setObjectName("gctf_cc_cutoff")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.gctf_cc_cutoff)
        self.label_24 = QtWidgets.QLabel(self.groupBox_Gctf_1)
        self.label_24.setObjectName("label_24")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.btn_gctf_executable = QtWidgets.QToolButton(self.groupBox_Gctf_1)
        self.btn_gctf_executable.setObjectName("btn_gctf_executable")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.btn_gctf_executable)
        self.gridLayout_6.addWidget(self.groupBox_Gctf_1, 0, 0, 1, 1)
        self.groupBox_Gctf_2 = QtWidgets.QGroupBox(self.Gctf)
        self.groupBox_Gctf_2.setObjectName("groupBox_Gctf_2")
        self.formLayout_7 = QtWidgets.QFormLayout(self.groupBox_Gctf_2)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_31 = QtWidgets.QLabel(self.groupBox_Gctf_2)
        self.label_31.setObjectName("label_31")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.gctf_apix = QtWidgets.QLineEdit(self.groupBox_Gctf_2)
        self.gctf_apix.setEnabled(False)
        self.gctf_apix.setObjectName("gctf_apix")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gctf_apix)
        self.label_32 = QtWidgets.QLabel(self.groupBox_Gctf_2)
        self.label_32.setObjectName("label_32")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.gctf_kV = QtWidgets.QLineEdit(self.groupBox_Gctf_2)
        self.gctf_kV.setEnabled(False)
        self.gctf_kV.setObjectName("gctf_kV")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.gctf_kV)
        self.label_33 = QtWidgets.QLabel(self.groupBox_Gctf_2)
        self.label_33.setObjectName("label_33")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.gctf_cs = QtWidgets.QLineEdit(self.groupBox_Gctf_2)
        self.gctf_cs.setEnabled(False)
        self.gctf_cs.setObjectName("gctf_cs")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.gctf_cs)
        self.label_40 = QtWidgets.QLabel(self.groupBox_Gctf_2)
        self.label_40.setObjectName("label_40")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.gctf_ac = QtWidgets.QLineEdit(self.groupBox_Gctf_2)
        self.gctf_ac.setEnabled(False)
        self.gctf_ac.setObjectName("gctf_ac")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.gctf_ac)
        self.gridLayout_6.addWidget(self.groupBox_Gctf_2, 0, 1, 1, 1)
        self.groupBox_Gctf_3 = QtWidgets.QGroupBox(self.Gctf)
        self.groupBox_Gctf_3.setObjectName("groupBox_Gctf_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_Gctf_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_Gctf_3)
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setStyleSheet("background-color: rgba(255, 255, 255);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 263, 589))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.label_34 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_34.setObjectName("label_34")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.gctf_defL = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.gctf_defL.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gctf_defL.setObjectName("gctf_defL")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.gctf_defL)
        self.label_35 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_35.setObjectName("label_35")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.gctf_defH = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.gctf_defH.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gctf_defH.setObjectName("gctf_defH")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.gctf_defH)
        self.label_36 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_36.setObjectName("label_36")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.gctf_defS = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.gctf_defS.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gctf_defS.setObjectName("gctf_defS")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.gctf_defS)
        self.label_37 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_37.setObjectName("label_37")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.gctf_astm = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.gctf_astm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gctf_astm.setObjectName("gctf_astm")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.gctf_astm)
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.label_78 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_78.setObjectName("label_78")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_78)
        self.gctf_phase_shift_L = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.gctf_phase_shift_L.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gctf_phase_shift_L.setObjectName("gctf_phase_shift_L")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.gctf_phase_shift_L)
        self.label_79 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_79.setObjectName("label_79")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_79)
        self.gctf_phase_shift_H = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.gctf_phase_shift_H.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gctf_phase_shift_H.setObjectName("gctf_phase_shift_H")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.gctf_phase_shift_H)
        self.label_80 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_80.setObjectName("label_80")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_80)
        self.gctf_phase_shift_S = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.gctf_phase_shift_S.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gctf_phase_shift_S.setObjectName("gctf_phase_shift_S")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.gctf_phase_shift_S)
        self.label_81 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_81.setObjectName("label_81")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_81)
        self.gctf_phase_shift_T = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.gctf_phase_shift_T.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gctf_phase_shift_T.setObjectName("gctf_phase_shift_T")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.gctf_phase_shift_T)
        self.label_29 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.label_82 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_82.setObjectName("label_82")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_82)
        self.gctf_resL = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.gctf_resL.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gctf_resL.setObjectName("gctf_resL")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.gctf_resL)
        self.label_83 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_83.setObjectName("label_83")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_83)
        self.gctf_resH = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.gctf_resH.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gctf_resH.setObjectName("gctf_resH")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.gctf_resH)
        self.label_85 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_85.setObjectName("label_85")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_85)
        self.gctf_do_Hres_ref = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.gctf_do_Hres_ref.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gctf_do_Hres_ref.setObjectName("gctf_do_Hres_ref")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.gctf_do_Hres_ref)
        self.label_86 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_86.setObjectName("label_86")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_86)
        self.gctf_Href_resL = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.gctf_Href_resL.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gctf_Href_resL.setObjectName("gctf_Href_resL")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.gctf_Href_resL)
        self.label_87 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_87.setObjectName("label_87")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_87)
        self.gctf_Href_resH = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.gctf_Href_resH.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gctf_Href_resH.setObjectName("gctf_Href_resH")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.gctf_Href_resH)
        self.label_84 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_84.setObjectName("label_84")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.label_84)
        self.gctf_Href_bfac = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.gctf_Href_bfac.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gctf_Href_bfac.setObjectName("gctf_Href_bfac")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.gctf_Href_bfac)
        self.label_43 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.label_43)
        self.label_44 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_44.setObjectName("label_44")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.label_44)
        self.gctf_bfac = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.gctf_bfac.setObjectName("gctf_bfac")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.gctf_bfac)
        self.label_45 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_45.setObjectName("label_45")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.label_45)
        self.gctf_B_resL = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.gctf_B_resL.setObjectName("gctf_B_resL")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.FieldRole, self.gctf_B_resL)
        self.label_46 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_46.setObjectName("label_46")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.LabelRole, self.label_46)
        self.gctf_B_resH = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.gctf_B_resH.setObjectName("gctf_B_resH")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.FieldRole, self.gctf_B_resH)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_5.addWidget(self.scrollArea)
        self.gridLayout_6.addWidget(self.groupBox_Gctf_3, 0, 2, 1, 1)
        self.groupBox_Gctf_4 = QtWidgets.QGroupBox(self.Gctf)
        self.groupBox_Gctf_4.setObjectName("groupBox_Gctf_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_Gctf_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.plainTextEdit_gctf = QtWidgets.QPlainTextEdit(self.groupBox_Gctf_4)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono L")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.plainTextEdit_gctf.setFont(font)
        self.plainTextEdit_gctf.setObjectName("plainTextEdit_gctf")
        self.horizontalLayout_4.addWidget(self.plainTextEdit_gctf)
        self.gridLayout_6.addWidget(self.groupBox_Gctf_4, 1, 0, 1, 3)
        self.tabWidget.addTab(self.Gctf, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 1, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 745, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_configurations = QtWidgets.QAction(MainWindow)
        self.actionLoad_configurations.setObjectName("actionLoad_configurations")
        self.actionSave_configurations = QtWidgets.QAction(MainWindow)
        self.actionSave_configurations.setObjectName("actionSave_configurations")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionMotioncor_manual = QtWidgets.QAction(MainWindow)
        self.actionMotioncor_manual.setObjectName("actionMotioncor_manual")
        self.actionGctf_manual = QtWidgets.QAction(MainWindow)
        self.actionGctf_manual.setObjectName("actionGctf_manual")
        self.actionRecent_configurations = QtWidgets.QAction(MainWindow)
        self.actionRecent_configurations.setObjectName("actionRecent_configurations")
        self.menuFile.addAction(self.actionSave_configurations)
        self.menuFile.addAction(self.actionLoad_configurations)
        self.menuFile.addAction(self.actionRecent_configurations)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MPIApp"))
        self.btn_Exit.setText(_translate("MainWindow", "Exit"))
        self.btn_Run.setText(_translate("MainWindow", "Run"))
        self.groupBox_Main_1.setTitle(_translate("MainWindow", "Setup Parameters"))
        self.label.setText(_translate("MainWindow", "Input Directory"))
        self.btnGain.setText(_translate("MainWindow", "Select File"))
        self.label_5.setText(_translate("MainWindow", "GPUs"))
        self.radio_tif.setText(_translate("MainWindow", "tif"))
        self.radio_mrc.setText(_translate("MainWindow", "mrc"))
        self.btnOutputDir.setText(_translate("MainWindow", "Select Directory"))
        self.btnInputDir.setText(_translate("MainWindow", "Select Directory"))
        self.GPU_0.setText(_translate("MainWindow", "0"))
        self.GPU_1.setText(_translate("MainWindow", "1"))
        self.GPU_2.setText(_translate("MainWindow", "2"))
        self.GPU_3.setText(_translate("MainWindow", "3"))
        self.GPU_4.setText(_translate("MainWindow", "4"))
        self.GPU_5.setText(_translate("MainWindow", "5"))
        self.GPU_6.setText(_translate("MainWindow", "6"))
        self.GPU_7.setText(_translate("MainWindow", "7"))
        self.GPU_8.setText(_translate("MainWindow", "8"))
        self.GPU_9.setText(_translate("MainWindow", "9"))
        self.label_4.setText(_translate("MainWindow", "File Extension"))
        self.label_3.setText(_translate("MainWindow", "Gain Reference"))
        self.label_2.setText(_translate("MainWindow", "Output Directory"))
        self.groupBox_Main_2.setTitle(_translate("MainWindow", "Microscope Parameters"))
        self.label_9.setText(_translate("MainWindow", "Spherical Aberration"))
        self.label_7.setText(_translate("MainWindow", "Pixel Size"))
        self.line_kV.setPlaceholderText(_translate("MainWindow", "300"))
        self.label_10.setText(_translate("MainWindow", "Amplitude Constrast"))
        self.line_cs.setPlaceholderText(_translate("MainWindow", "2.62"))
        self.label_63.setText(_translate("MainWindow", "mm"))
        self.line_dose_per_frame.setPlaceholderText(_translate("MainWindow", "1"))
        self.line_ac.setPlaceholderText(_translate("MainWindow", "0.1"))
        self.label_8.setText(_translate("MainWindow", "Dose per Frame"))
        self.label_60.setText(_translate("MainWindow", "kV"))
        self.line_apix.setPlaceholderText(_translate("MainWindow", "0.53"))
        self.label_61.setText(_translate("MainWindow", "A / pix"))
        self.label_6.setText(_translate("MainWindow", "Voltage"))
        self.label_62.setText(_translate("MainWindow", "e / A²"))
        self.groupBox_Main_3.setTitle(_translate("MainWindow", "Additional Files to process"))
        self.btn_addFiles.setText(_translate("MainWindow", "+"))
        self.btn_removeFiles.setText(_translate("MainWindow", "-"))
        self.btn_removeFiles.setShortcut(_translate("MainWindow", "Del"))
        self.btn_clearAllFiles.setText(_translate("MainWindow", "clear all"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Main), _translate("MainWindow", "Main"))
        self.groupBox_Motioncor_1.setTitle(_translate("MainWindow", "Setup"))
        self.label_26.setText(_translate("MainWindow", "Timeout"))
        self.motioncor_timeout.setToolTip(_translate("MainWindow", "Timeout in seconds.\n"
"If the program takes longer than this to run, it will abort"))
        self.label_64.setText(_translate("MainWindow", "Trials"))
        self.label_23.setToolTip(_translate("MainWindow", "defaults to \'motioncor\'"))
        self.label_23.setText(_translate("MainWindow", "Executable"))
        self.btn_motioncor_executable.setToolTip(_translate("MainWindow", "select the path to the executable"))
        self.btn_motioncor_executable.setText(_translate("MainWindow", "..."))
        self.groupBox_Motioncor_2.setToolTip(_translate("MainWindow", "this values are defined by the settings in the Main tab"))
        self.groupBox_Motioncor_2.setTitle(_translate("MainWindow", "Defaults"))
        self.label_18.setText(_translate("MainWindow", "FmDose"))
        self.motioncor_FmDose.setToolTip(_translate("MainWindow", "Frame dose in e/A^2. If not specified, dose\n"
"weighting will be skipped."))
        self.label_13.setText(_translate("MainWindow", "kV"))
        self.motioncor_kV.setToolTip(_translate("MainWindow", "High tension in kV needed for dose weighting.\n"
"Default is 300."))
        self.label_15.setText(_translate("MainWindow", "PixSize"))
        self.motioncor_PixSize.setToolTip(_translate("MainWindow", "Pixel size in A of input stack in angstrom. If not\n"
"specified, dose weighting will be skipped."))
        self.groupBox_Motioncor_3.setTitle(_translate("MainWindow", "Parameters"))
        self.label_12.setText(_translate("MainWindow", "Iter"))
        self.motioncor_Iter.setToolTip(_translate("MainWindow", "Maximum iterations for iterative alignment,\n"
"default 5 iterations."))
        self.label_17.setText(_translate("MainWindow", "InitDose"))
        self.motioncor_InitDose.setToolTip(_translate("MainWindow", "Initial dose received before stack is acquired"))
        self.label_11.setText(_translate("MainWindow", "Patch"))
        self.motioncor_Patch.setToolTip(_translate("MainWindow", "Number of patches to be used for patch based alignment,\n"
"default 0 0 corresponding full frame alignment."))
        self.label_28.setText(_translate("MainWindow", "Mag"))
        self.motioncor_Mag.setToolTip(_translate("MainWindow", "1. Correct anisotropic magnification by stretching\n"
"   image along the major axis, the axis where the\n"
"   lower magificantion is detected.\n"
"2. Three inputs are needed including magnifications\n"
"   along major and minor axes and the angle of the\n"
"   major axis relative to the image x-axis in degree.\n"
"3. By default no correction is performed."))
        self.label_16.setText(_translate("MainWindow", "FtBin"))
        self.motioncor_FtBin.setToolTip(_translate("MainWindow", "Binning performed in Fourier space, default 1.0."))
        self.groupBox_Motioncor_4.setTitle(_translate("MainWindow", "Misc"))
        self.label_21.setText(_translate("MainWindow", "Group"))
        self.motioncor_Group.setToolTip(_translate("MainWindow", "Group every specified number of frames by adding\n"
"them together. The alignment is then performed\n"
"on the summed frames. By default, no grouping\n"
"is performed."))
        self.label_22.setText(_translate("MainWindow", "FmRef"))
        self.motioncor_FmRef.setToolTip(_translate("MainWindow", "Specify which frame to be the reference to which\n"
"all other frames are aligned. By default (-1) the\n"
"the central frame is chosen. The central frame is\n"
"at N/2 based upon zero indexing where N is the\n"
"number of frames that will be summed, i.e., not\n"
"including the frames thrown away."))
        self.label_14.setText(_translate("MainWindow", "Bft"))
        self.motioncor_Bft.setToolTip(_translate("MainWindow", "B-Factor for alignment, default 100."))
        self.label_19.setText(_translate("MainWindow", "Throw"))
        self.motioncor_Throw.setToolTip(_translate("MainWindow", "Throw initial number of frames, default is 0"))
        self.label_47.setText(_translate("MainWindow", "Trunc"))
        self.motioncor_Trunc.setToolTip(_translate("MainWindow", "Truncate last number of frames, default is 0"))
        self.groupBox_Motioncor_5.setTitle(_translate("MainWindow", "Additional parameters"))
        self.plainTextEdit_motioncor.setPlaceholderText(_translate("MainWindow", "e.g. -Crop 0 -Bft 100"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Motioncor), _translate("MainWindow", "Motioncor"))
        self.groupBox_Gctf_1.setTitle(_translate("MainWindow", "Setup"))
        self.label_38.setText(_translate("MainWindow", "Timeout"))
        self.gctf_timeout.setToolTip(_translate("MainWindow", "Timeout in seconds.\n"
"If the program takes longer than this to run, it will abort"))
        self.label_39.setText(_translate("MainWindow", "Trials"))
        self.label_42.setText(_translate("MainWindow", "CC Cutoff"))
        self.gctf_cc_cutoff.setToolTip(_translate("MainWindow", "Cross correlation cutoff value for estimating the resolution"))
        self.label_24.setToolTip(_translate("MainWindow", "defaults to \'gctf\'"))
        self.label_24.setText(_translate("MainWindow", "Executable"))
        self.btn_gctf_executable.setToolTip(_translate("MainWindow", "select the path to the executable"))
        self.btn_gctf_executable.setText(_translate("MainWindow", "..."))
        self.groupBox_Gctf_2.setTitle(_translate("MainWindow", "Defaults"))
        self.label_31.setText(_translate("MainWindow", "apix"))
        self.gctf_apix.setToolTip(_translate("MainWindow", "Pixel size"))
        self.label_32.setText(_translate("MainWindow", "kV"))
        self.gctf_kV.setToolTip(_translate("MainWindow", "High tension in Kilovolt"))
        self.label_33.setText(_translate("MainWindow", "cs"))
        self.gctf_cs.setToolTip(_translate("MainWindow", "Spherical aberration, in  millimeter"))
        self.label_40.setText(_translate("MainWindow", "ac"))
        self.gctf_ac.setToolTip(_translate("MainWindow", "Amplitude contrast; normal range 0.04~0.1; pure ice 0.04, carbon 0.1; but doesn\'t matter too much if using wrong value"))
        self.groupBox_Gctf_3.setTitle(_translate("MainWindow", "Additional parameters"))
        self.label_30.setText(_translate("MainWindow", "Defocus options"))
        self.label_34.setText(_translate("MainWindow", "defL"))
        self.gctf_defL.setToolTip(_translate("MainWindow", "Lowest defocus value to search, in angstrom"))
        self.label_35.setText(_translate("MainWindow", "defH"))
        self.gctf_defH.setToolTip(_translate("MainWindow", "Highest defocus value to search, in angstrom"))
        self.label_36.setText(_translate("MainWindow", "defS"))
        self.gctf_defS.setToolTip(_translate("MainWindow", "Step of defocus value used to search, in angstrom"))
        self.label_37.setText(_translate("MainWindow", "astm"))
        self.gctf_astm.setToolTip(_translate("MainWindow", "Estimated astigmation in angstrom, don\'t need to be accurate, within 0.1~10 times is OK"))
        self.label_25.setText(_translate("MainWindow", "Phase plate options"))
        self.label_78.setText(_translate("MainWindow", "phase_shift_L"))
        self.gctf_phase_shift_L.setToolTip(_translate("MainWindow", "User defined phase shift, lowest phase shift,  in degree; typically, ~90.0 for micrographs using phase plate "))
        self.label_79.setText(_translate("MainWindow", "phase_shift_H"))
        self.gctf_phase_shift_H.setToolTip(_translate("MainWindow", "User defined phase shift, highest phase shift, final range will be (phase_shift_L, phase_shift_H)"))
        self.label_80.setText(_translate("MainWindow", "phase_shift_S"))
        self.gctf_phase_shift_S.setToolTip(_translate("MainWindow", "User defined phase shift search step; don\'t worry about the accuracy; this is just the search step, Gctf will refine the phase shift anyway."))
        self.label_81.setText(_translate("MainWindow", "phase_shift_T"))
        self.gctf_phase_shift_T.setToolTip(_translate("MainWindow", "Phase shift target in the search; 1: CCC; 2: resolution limit;"))
        self.label_29.setText(_translate("MainWindow", "Resolution options"))
        self.label_82.setText(_translate("MainWindow", "resL"))
        self.gctf_resL.setToolTip(_translate("MainWindow", "Lowest Resolution to be used for search, in angstrom"))
        self.label_83.setText(_translate("MainWindow", "resH"))
        self.gctf_resH.setToolTip(_translate("MainWindow", "Highest Resolution to be used for search, in angstrom"))
        self.label_85.setText(_translate("MainWindow", "do_Hres_ref"))
        self.gctf_do_Hres_ref.setToolTip(_translate("MainWindow", "Whether to do High-resolution refinement or not, very useful for selecting high quality micrographs"))
        self.label_86.setText(_translate("MainWindow", "Href_resL"))
        self.gctf_Href_resL.setToolTip(_translate("MainWindow", "Lowest Resolution  to be used for High-resolution refinement, in angstrom"))
        self.label_87.setText(_translate("MainWindow", "Href_resH"))
        self.gctf_Href_resH.setToolTip(_translate("MainWindow", "Highest Resolution  to be used for High-resolution refinement, in angstrom"))
        self.label_84.setText(_translate("MainWindow", "Href_bfac"))
        self.gctf_Href_bfac.setToolTip(_translate("MainWindow", "Bfactor to be used for High-resolution refinement,A^2 NOT the estimated micrograph Bfactor!"))
        self.label_43.setText(_translate("MainWindow", "Bfactor options"))
        self.label_44.setText(_translate("MainWindow", "bfac"))
        self.gctf_bfac.setToolTip(_translate("MainWindow", "Bfactor used to decrease high resolution amplitude,A^2; NOT the estimated micrograph Bfactor! suggested range 50~300 except using \'REBS method\'."))
        self.label_45.setText(_translate("MainWindow", "B_resL"))
        self.gctf_B_resL.setToolTip(_translate("MainWindow", "Lowest resolution for Bfactor estimation; This output Bfactor is the real estimation of the micrograph"))
        self.label_46.setText(_translate("MainWindow", "B_resH"))
        self.gctf_B_resH.setToolTip(_translate("MainWindow", "Highest resolution for Bfactor estimation"))
        self.groupBox_Gctf_4.setTitle(_translate("MainWindow", "Additional parameters"))
        self.plainTextEdit_gctf.setPlaceholderText(_translate("MainWindow", "e.g. --boxsize 1024 --convsize 30"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Gctf), _translate("MainWindow", "Gctf"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_configurations.setText(_translate("MainWindow", "Load configurations..."))
        self.actionSave_configurations.setText(_translate("MainWindow", "Save configurations"))
        self.actionExit.setText(_translate("MainWindow", "Quit"))
        self.actionMotioncor_manual.setText(_translate("MainWindow", "Motioncor manual"))
        self.actionGctf_manual.setText(_translate("MainWindow", "Gctf manual"))
        self.actionRecent_configurations.setText(_translate("MainWindow", "Recent configurations"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

